### ISSUE TITLE
It's not working with whmcs 7.10

### ISSUE THREAD

**Issue by wpexpertinbd** [oneall/social-login-whmcs#2]
Hi, I found that this module not working with whmcs latest update 7.10 but it was working fine upto 7.9.2, can anyone fix the issue & let me know it. Below i copy paste the error.....

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

ArgumentCountError: Too few arguments to function WHMCS\Authentication\Client::generateClientLoginHash(), 3 passed in /home/example/public_html/modules/addons/oneall_social_login/assets/toolbox.php on line 316 and exactly 4 expected in /home/example/public_html/vendor/whmcs/whmcs-foundation/lib/Authentication/Client.php:0
Stack trace:
#0 /home/example/public_html/modules/addons/oneall_social_login/assets/toolbox.php(316): WHMCS\Authentication\Client::generateClientLoginHash(520, '', '$2y$10$CU155441PN9gl...')
#1 /home/example/public_html/modules/addons/oneall_social_login/hooks.php(110): oneall_social_login_login_userid(520, '203.254.512.01')
#2 /home/example/public_html/includes/hookfunctions.php(0): oneall_social_login_callback(Array)
#3 /home/example/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): run_hook('ClientAreaPage', Array)
#4 /home/example/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): WHMCS\ClientArea->runOutputHooks()
#5 /home/example/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): WHMCS\ClientArea->outputWithoutExit()
#6 /home/example/public_html/vendor/whmcs/whmcs-foundation/lib/Http/Message/AbstractViewableResponse.php(0): WHMCS\ClientArea->getOutputContent()
#7 /home/example/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php(27): WHMCS\Http\Message\AbstractViewableResponse->getBody()
#8 /home/example/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php(34): Zend\Diactoros\Response\SapiEmitter->injectContentLength(Object(WHMCS\ClientArea))
#9 /home/example/public_html/clientarea.php(0): Zend\Diactoros\Response\SapiEmitter->emit(Object(WHMCS\ClientArea))
#10 {main}

**Comment by SchlesserClaude** [comment]
Thank you very much for the bug report. This issue was fixed in the latest version.
